// This file is generated by scripts/generate-search-routes.mjs.
// Run `npm run search:index` to refresh it manually. Dev and production builds do this automatically.

export const GENERATED_SITE_SEARCH_ROUTES = [
    {
        "title": "Home",
        "href": "/",
        "description": "TaskTornado landing page",
        "icon": "Home02",
        "category": "About",
        "keywords": [
            "home",
            "about"
        ]
    },
    {
        "title": "Account Eligibility",
        "href": "/account-eligibility",
        "description": "Open the Account Eligibility page",
        "icon": "Login01",
        "category": "Account",
        "keywords": [
            "account eligibility",
            "account",
            "eligibility"
        ]
    },
    {
        "title": "AI Guidelines",
        "href": "/ai-guidelines",
        "description": "Open the AI Guidelines page",
        "icon": "Star",
        "category": "About",
        "keywords": [
            "ai guidelines",
            "about",
            "ai",
            "guidelines"
        ]
    },
    {
        "title": "Blog",
        "href": "/blog",
        "description": "TaskTornado stories, guides, and updates",
        "icon": "Blogger",
        "category": "Blog",
        "keywords": [
            "blog"
        ]
    },
    {
        "title": "Adaptive Quizzes",
        "href": "/blog/adaptive-quizzes",
        "description": "Open the Adaptive Quizzes page",
        "icon": "Quiz04",
        "category": "Blog",
        "keywords": [
            "adaptive quizzes",
            "blog",
            "adaptive",
            "quizzes"
        ]
    },
    {
        "title": "Facehash",
        "href": "/blog/facehash",
        "description": "Open the Facehash page",
        "icon": "Fingerprint",
        "category": "Blog",
        "keywords": [
            "facehash",
            "blog"
        ]
    },
    {
        "title": "Flashcards Reimagined",
        "href": "/blog/flashcards-reimagined",
        "description": "Open the Flashcards Reimagined page",
        "icon": "Cards01",
        "category": "Blog",
        "keywords": [
            "flashcards reimagined",
            "blog",
            "flashcards",
            "reimagined"
        ]
    },
    {
        "title": "Focus Timer",
        "href": "/blog/focus-timer",
        "description": "Open the Focus Timer page",
        "icon": "Blogger",
        "category": "Blog",
        "keywords": [
            "focus timer",
            "blog",
            "focus",
            "timer"
        ]
    },
    {
        "title": "Global Translation",
        "href": "/blog/global-translation",
        "description": "Open the Global Translation page",
        "icon": "Translate",
        "category": "Blog",
        "keywords": [
            "global translation",
            "blog",
            "global",
            "translation"
        ]
    },
    {
        "title": "Grade Calculator",
        "href": "/blog/grade-calculator",
        "description": "Open the Grade Calculator page",
        "icon": "ChartAnalysis",
        "category": "Blog",
        "keywords": [
            "grade calculator",
            "blog",
            "grade",
            "calculator"
        ]
    },
    {
        "title": "Learning Center",
        "href": "/blog/learning-center",
        "description": "Open the Learning Center page",
        "icon": "Blogger",
        "category": "Blog",
        "keywords": [
            "learning center",
            "blog",
            "learning",
            "center"
        ]
    },
    {
        "title": "Learning Through Play",
        "href": "/blog/learning-through-play",
        "description": "Open the Learning Through Play page",
        "icon": "Blogger",
        "category": "Blog",
        "keywords": [
            "learning through play",
            "blog",
            "learning",
            "through",
            "play"
        ]
    },
    {
        "title": "Making Of Aurora",
        "href": "/blog/making-of-aurora",
        "description": "Open the Making Of Aurora page",
        "icon": "Blogger",
        "category": "Blog",
        "keywords": [
            "making of aurora",
            "blog",
            "making",
            "of",
            "aurora"
        ]
    },
    {
        "title": "Meet Aurora",
        "href": "/blog/meet-aurora",
        "description": "Open the Meet Aurora page",
        "icon": "Blogger",
        "category": "Blog",
        "keywords": [
            "meet aurora",
            "blog",
            "meet",
            "aurora"
        ]
    },
    {
        "title": "Peer Discussions",
        "href": "/blog/peer-discussions",
        "description": "Open the Peer Discussions page",
        "icon": "Chat",
        "category": "Blog",
        "keywords": [
            "peer discussions",
            "blog",
            "peer",
            "discussions"
        ]
    },
    {
        "title": "Research Hub",
        "href": "/blog/research-hub",
        "description": "Open the Research Hub page",
        "icon": "Blogger",
        "category": "Blog",
        "keywords": [
            "research hub",
            "blog",
            "research",
            "hub"
        ]
    },
    {
        "title": "Smart Calendar",
        "href": "/blog/smart-calendar",
        "description": "Open the Smart Calendar page",
        "icon": "Calendar02",
        "category": "Blog",
        "keywords": [
            "smart calendar",
            "blog",
            "smart",
            "calendar"
        ]
    },
    {
        "title": "Study Groups",
        "href": "/blog/study-groups",
        "description": "Open the Study Groups page",
        "icon": "UserGroup03",
        "category": "Blog",
        "keywords": [
            "study groups",
            "blog",
            "study",
            "groups"
        ]
    },
    {
        "title": "The Command Center",
        "href": "/blog/the-command-center",
        "description": "Open the The Command Center page",
        "icon": "Blogger",
        "category": "Blog",
        "keywords": [
            "the command center",
            "blog",
            "the",
            "command",
            "center"
        ]
    },
    {
        "title": "Writing Companion",
        "href": "/blog/writing-companion",
        "description": "Open the Writing Companion page",
        "icon": "AiContentGenerator02",
        "category": "Blog",
        "keywords": [
            "writing companion",
            "blog",
            "writing",
            "companion"
        ]
    },
    {
        "title": "Calendar",
        "href": "/calendar",
        "description": "Plan assignments, tests, and school events",
        "icon": "Calendar02",
        "category": "School",
        "keywords": [
            "calendar",
            "school",
            "schedule",
            "events",
            "dates",
            "planner",
            "due"
        ]
    },
    {
        "title": "Cat Shop",
        "href": "/cat-shop",
        "description": "Open the Cat Shop page",
        "icon": "LayoutGrid",
        "category": "App",
        "keywords": [
            "cat shop",
            "app",
            "cat",
            "shop"
        ]
    },
    {
        "title": "Changelog",
        "href": "/changelog",
        "description": "Open the Changelog page",
        "icon": "Star",
        "category": "About",
        "keywords": [
            "changelog",
            "about"
        ]
    },
    {
        "title": "Color Match",
        "href": "/color-match",
        "description": "Open the Color Match page",
        "icon": "Gameboy",
        "category": "Games",
        "keywords": [
            "color match",
            "games",
            "color",
            "match"
        ]
    },
    {
        "title": "Complete Signup",
        "href": "/complete-signup",
        "description": "Open the Complete Signup page",
        "icon": "Login01",
        "category": "Account",
        "keywords": [
            "complete signup",
            "account",
            "complete",
            "signup"
        ]
    },
    {
        "title": "Dashboard",
        "href": "/dashboard",
        "description": "Classes, assignments, tests, and progress",
        "icon": "Home02",
        "category": "App",
        "keywords": [
            "dashboard",
            "app",
            "home",
            "overview",
            "command center",
            "classes",
            "homework"
        ]
    },
    {
        "title": "Discussion Boards",
        "href": "/discussions",
        "description": "Ask questions and share academic resources",
        "icon": "Chat",
        "category": "School",
        "keywords": [
            "discussion boards",
            "school",
            "discussions"
        ]
    },
    {
        "title": "Features",
        "href": "/features",
        "description": "Open the Features page",
        "icon": "Star",
        "category": "About",
        "keywords": [
            "features",
            "about"
        ]
    },
    {
        "title": "Flashcards",
        "href": "/flashcards",
        "description": "Create and study flashcard decks",
        "icon": "Cards01",
        "category": "School",
        "keywords": [
            "flashcards",
            "school",
            "flash cards",
            "cards",
            "memorize",
            "review",
            "study deck"
        ]
    },
    {
        "title": "Forgot Password",
        "href": "/forgot-password",
        "description": "Open the Forgot Password page",
        "icon": "Login01",
        "category": "Account",
        "keywords": [
            "forgot password",
            "account",
            "forgot",
            "password"
        ]
    },
    {
        "title": "Games",
        "href": "/games",
        "description": "Browse all study breaks and games",
        "icon": "Gameboy",
        "category": "Games",
        "keywords": [
            "games"
        ]
    },
    {
        "title": "Grade Calculator",
        "href": "/grade-calculator",
        "description": "Calculate and save weighted class grades",
        "icon": "ChartAnalysis",
        "category": "Tools",
        "keywords": [
            "grade calculator",
            "tools",
            "grade",
            "calculator",
            "grades",
            "weighted grades",
            "gpa",
            "percentage",
            "average",
            "powerschool",
            "smart paste"
        ]
    },
    {
        "title": "Grader",
        "href": "/grader",
        "description": "Review writing against a rubric",
        "icon": "ChartAnalysis",
        "category": "Tools",
        "keywords": [
            "grader",
            "tools"
        ]
    },
    {
        "title": "Public Grade Calculator",
        "href": "/grades",
        "description": "Open the Public Grade Calculator page",
        "icon": "ChartAnalysis",
        "category": "Tools",
        "keywords": [
            "public grade calculator",
            "tools",
            "grades"
        ]
    },
    {
        "title": "Groups",
        "href": "/groups",
        "description": "Collaborate with classmates in study groups",
        "icon": "UserGroup03",
        "category": "School",
        "keywords": [
            "groups",
            "school"
        ]
    },
    {
        "title": "Dashboard",
        "href": "/guardian/dashboard",
        "description": "Open the Dashboard page",
        "icon": "Security01",
        "category": "App",
        "keywords": [
            "dashboard",
            "app",
            "guardian"
        ]
    },
    {
        "title": "Link",
        "href": "/guardian/link",
        "description": "Open the Link page",
        "icon": "Security01",
        "category": "Account",
        "keywords": [
            "link",
            "account",
            "guardian"
        ]
    },
    {
        "title": "Guardians",
        "href": "/guardians",
        "description": "Open the Guardians page",
        "icon": "Security01",
        "category": "About",
        "keywords": [
            "guardians",
            "about"
        ]
    },
    {
        "title": "FaceHash Playground",
        "href": "/hash",
        "description": "Open the FaceHash Playground page",
        "icon": "Fingerprint",
        "category": "Tools",
        "keywords": [
            "facehash playground",
            "tools",
            "hash"
        ]
    },
    {
        "title": "Privacy",
        "href": "/legal/privacy",
        "description": "Open the Privacy page",
        "icon": "Security01",
        "category": "About",
        "keywords": [
            "privacy",
            "about",
            "legal"
        ]
    },
    {
        "title": "Terms",
        "href": "/legal/terms",
        "description": "Open the Terms page",
        "icon": "Security01",
        "category": "About",
        "keywords": [
            "terms",
            "about",
            "legal"
        ]
    },
    {
        "title": "Letter",
        "href": "/letter",
        "description": "Open the Letter page",
        "icon": "Star",
        "category": "About",
        "keywords": [
            "letter",
            "about"
        ]
    },
    {
        "title": "Login",
        "href": "/login",
        "description": "Open the Login page",
        "icon": "Login01",
        "category": "Account",
        "keywords": [
            "login",
            "account"
        ]
    },
    {
        "title": "Math Sprint",
        "href": "/math-sprint",
        "description": "Open the Math Sprint page",
        "icon": "Gameboy",
        "category": "Games",
        "keywords": [
            "math sprint",
            "games",
            "math",
            "sprint"
        ]
    },
    {
        "title": "Memory Match",
        "href": "/memory-match",
        "description": "Open the Memory Match page",
        "icon": "Gameboy",
        "category": "Games",
        "keywords": [
            "memory match",
            "games",
            "memory",
            "match"
        ]
    },
    {
        "title": "Parental Consent",
        "href": "/parental-consent",
        "description": "Open the Parental Consent page",
        "icon": "Login01",
        "category": "Account",
        "keywords": [
            "parental consent",
            "account",
            "parental",
            "consent"
        ]
    },
    {
        "title": "Pricing",
        "href": "/pricing",
        "description": "Open the Pricing page",
        "icon": "Star",
        "category": "About",
        "keywords": [
            "pricing",
            "about"
        ]
    },
    {
        "title": "Public Calendar",
        "href": "/publiccalendar",
        "description": "Open the Public Calendar page",
        "icon": "Calendar02",
        "category": "Tools",
        "keywords": [
            "public calendar",
            "tools",
            "publiccalendar"
        ]
    },
    {
        "title": "Tv",
        "href": "/publiccalendar/tv",
        "description": "Open the Tv page",
        "icon": "Calendar02",
        "category": "About",
        "keywords": [
            "tv",
            "about",
            "publiccalendar"
        ]
    },
    {
        "title": "Interactive Quizzes",
        "href": "/quiz",
        "description": "Create, save, and take practice quizzes",
        "icon": "Quiz04",
        "category": "School",
        "keywords": [
            "interactive quizzes",
            "school",
            "quiz"
        ]
    },
    {
        "title": "Reaction Time",
        "href": "/reaction-time",
        "description": "Open the Reaction Time page",
        "icon": "Gameboy",
        "category": "Games",
        "keywords": [
            "reaction time",
            "games",
            "reaction",
            "time"
        ]
    },
    {
        "title": "Reset Password",
        "href": "/reset-password",
        "description": "Open the Reset Password page",
        "icon": "Login01",
        "category": "Account",
        "keywords": [
            "reset password",
            "account",
            "reset",
            "password"
        ]
    },
    {
        "title": "Settings",
        "href": "/settings",
        "description": "Account, appearance, and app preferences",
        "icon": "Settings02",
        "category": "App",
        "keywords": [
            "settings",
            "app"
        ]
    },
    {
        "title": "Signup",
        "href": "/signup",
        "description": "Open the Signup page",
        "icon": "Login01",
        "category": "Account",
        "keywords": [
            "signup",
            "account"
        ]
    },
    {
        "title": "Snake",
        "href": "/snake",
        "description": "Open the Snake page",
        "icon": "Gameboy",
        "category": "Games",
        "keywords": [
            "snake",
            "games"
        ]
    },
    {
        "title": "Task Tower",
        "href": "/task-tower",
        "description": "Open the Task Tower page",
        "icon": "Gameboy",
        "category": "Games",
        "keywords": [
            "task tower",
            "games",
            "task",
            "tower"
        ]
    },
    {
        "title": "Teachers",
        "href": "/teachers",
        "description": "Open the Teachers page",
        "icon": "GraduationCap",
        "category": "About",
        "keywords": [
            "teachers",
            "about"
        ]
    },
    {
        "title": "Tests",
        "href": "/tests",
        "description": "View and manage tests and exams",
        "icon": "GraduationCap",
        "category": "School",
        "keywords": [
            "tests",
            "school",
            "exam",
            "quiz",
            "assessment",
            "beta",
            "alpha"
        ]
    },
    {
        "title": "Translate",
        "href": "/translate",
        "description": "Translate text between languages",
        "icon": "Translate",
        "category": "Tools",
        "keywords": [
            "translate",
            "tools"
        ]
    },
    {
        "title": "Tutorials",
        "href": "/tutorials",
        "description": "Browse TaskTornado guides and tutorials",
        "icon": "HelpCircle",
        "category": "Help",
        "keywords": [
            "tutorials",
            "help"
        ]
    },
    {
        "title": "Csv Import",
        "href": "/tutorials/csv-import",
        "description": "Open the Csv Import page",
        "icon": "HelpCircle",
        "category": "Help",
        "keywords": [
            "csv import",
            "help",
            "tutorials",
            "csv",
            "import"
        ]
    },
    {
        "title": "Onboarding",
        "href": "/tutorials/onboarding",
        "description": "Open the Onboarding page",
        "icon": "HelpCircle",
        "category": "Help",
        "keywords": [
            "onboarding",
            "help",
            "tutorials"
        ]
    },
    {
        "title": "Recurring Homeworks",
        "href": "/tutorials/recurring-homeworks",
        "description": "Open the Recurring Homeworks page",
        "icon": "HelpCircle",
        "category": "Help",
        "keywords": [
            "recurring homeworks",
            "help",
            "tutorials",
            "recurring",
            "homeworks"
        ]
    },
    {
        "title": "Starring Homeworks",
        "href": "/tutorials/starring-homeworks",
        "description": "Open the Starring Homeworks page",
        "icon": "HelpCircle",
        "category": "Help",
        "keywords": [
            "starring homeworks",
            "help",
            "tutorials",
            "starring",
            "homeworks"
        ]
    },
    {
        "title": "Test Details",
        "href": "/tutorials/test-details",
        "description": "Open the Test Details page",
        "icon": "GraduationCap",
        "category": "Help",
        "keywords": [
            "test details",
            "help",
            "tutorials",
            "test",
            "details"
        ]
    },
    {
        "title": "Tv",
        "href": "/tv",
        "description": "Open the Tv page",
        "icon": "Star",
        "category": "About",
        "keywords": [
            "tv",
            "about"
        ]
    },
    {
        "title": "Typing Speed",
        "href": "/typing-speed",
        "description": "Open the Typing Speed page",
        "icon": "Gameboy",
        "category": "Games",
        "keywords": [
            "typing speed",
            "games",
            "typing",
            "speed"
        ]
    },
    {
        "title": "Web Saves",
        "href": "/web-saves",
        "description": "Search saved links, bookmarks, and folders",
        "icon": "Bookmark03",
        "category": "Tools",
        "keywords": [
            "web saves",
            "tools",
            "web",
            "saves",
            "links",
            "bookmarks",
            "websites",
            "folders"
        ]
    },
    {
        "title": "Word Scramble",
        "href": "/word-scramble",
        "description": "Open the Word Scramble page",
        "icon": "Gameboy",
        "category": "Games",
        "keywords": [
            "word scramble",
            "games",
            "word",
            "scramble"
        ]
    },
    {
        "title": "Word Counter",
        "href": "/wordcount",
        "description": "Open the Word Counter page",
        "icon": "LayoutGrid",
        "category": "Tools",
        "keywords": [
            "word counter",
            "tools",
            "wordcount"
        ]
    },
    {
        "title": "Writing Assistant",
        "href": "/writing-assist",
        "description": "Draft, revise, and improve writing",
        "icon": "AiContentGenerator02",
        "category": "Tools",
        "keywords": [
            "writing assistant",
            "tools",
            "writing",
            "assist",
            "essay",
            "editor",
            "compose",
            "grammar"
        ]
    }
] as const;

export const GENERATED_SEARCH_EXCLUDED_ROUTES = [
    "/hash/eyes",
    "/images",
    "/mail",
    "/signup-old"
] as const;
