import { HugeiconsIcon } from '@hugeicons/react';
import {
  CalculateIcon,
  Book01Icon,
  Book02Icon,
  Book03Icon,
  Book04Icon,
  AudioBook01Icon,
  AudioBook02Icon,
  AudioBook03Icon,
  AudioBook04Icon,
  Atom01Icon,
  Atom02Icon,
  MicroscopeIcon,
  GlobeIcon,
  Globe02Icon,
  MapsSquare02Icon,
  MazeIcon,
  MoreVerticalIcon,
  MusicNote01Icon,
  MusicNote02Icon,
  MusicNote03Icon,
  MusicNote04Icon,
  MusicThreeIcon,
  FileMusicIcon,
  File02Icon,
  FileEmpty02Icon,
  EyeIcon,
  ArtboardIcon,
  PenTool01Icon,
  PenTool02Icon,
  PenTool03Icon,
  PencilEdit01Icon,
  PencilIcon,
  PinIcon,
  PaintBoardIcon,
  PisaTowerIcon,
  CodeIcon,
  CodeSimpleIcon,
  CodeSquareIcon,
  BinaryCodeIcon,
  WorkoutSportIcon,
  EquipmentGym01Icon,
  EquipmentGym02Icon,
  EquipmentGym03Icon,
  GymnasticIcon,
  LanguageCircleIcon,
  LanguageSquareIcon,
  LanguageSkillIcon,
  Login01Icon,
  SchoolIcon,
  School01Icon,
  GraduationScrollIcon,
  GraduationCap,
  Mortarboard02Icon,
  AddressBookIcon,
  FilePenIcon,
  FileUpIcon,
  Download02Icon,
  Rocket02Icon,
  Camera01Icon,
  LayoutGridIcon,
  AiMagicIcon,
  Search01Icon,
  Cards01Icon,
  Quiz04Icon,
  AiContentGenerator02Icon,
  TranslateIcon,
  Share03Icon,
  NewTwitterIcon,
  Linkedin02Icon,
  HashtagIcon,
  BloggerIcon,
  MailSend01Icon,
  UserGroup03Icon,
  ChatIcon,
  HelpCircleIcon,
  GoogleDocIcon,
  Video01Icon,
  Timer01Icon,
  Clock01Icon,
  Bookmark03Icon,
  ChartAnalysisIcon,
  Wifi02Icon,
  WifiError02Icon,
  LogoutCircle02Icon,
  Settings02Icon,
  ThumbsUpIcon,
  Pen02Icon,
  PlusSignIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp02Icon,
  PlayIcon,
  PartyIcon,
  KeyboardIcon,
  PauseIcon,
  Home02Icon,
  Calendar02Icon,
  CalendarMinus02Icon,
  CalendarRemove01Icon,
  FilterIcon,
  AlertCircleIcon,
  CancelCircleIcon,
  MinusSignCircleIcon,
  Delete02Icon,
  Folder02Icon,
  LinkSquare02Icon,
  Folder03Icon,
  FolderAddIcon,
  Cancel01Icon,
  ClipboardPasteIcon,
  CircleLock01Icon,
  AiSecurity01Icon,
  WorkHistoryIcon,
  CreditCardIcon,
  News01Icon,
  FingerPrintIcon,
  ClipboardIcon,
  SparklesIcon,
  VolumeHighIcon,
  Copy01Icon,
  StarIcon,
  ZapIcon,
  CheckmarkCircle02Icon,
  RepeatIcon,
  Rotate01Icon,
  LayoutIcon,
  Layers01Icon,
  ArchiveIcon,
  LoaderPinwheelIcon,
  CrownIcon,
  Crown02Icon,
  Crown03Icon,
  Award01Icon,
  Sword03Icon,
  UserGroupIcon,
  UserMultipleIcon,
  WaveIcon,
  Message01Icon,
  Message02Icon,
  Link01Icon,
  Link02Icon,
  ScrollIcon,
  LaptopIcon,
  BrainIcon,
  Target01Icon,
  WalkingIcon,
  BoatIcon,
  Playlist03Icon,
  TheaterIcon,
  TextFontIcon,
  CanvasIcon,
  WebDesign01Icon,
  Target02Icon,
  CompassIcon,
  MapsIcon,
  LightbulbOffIcon,
  // Math icons
  MathIcon,
  BoardMathIcon,
  AbacusIcon,
  AbsoluteIcon,
  AcuteIcon,
  FirstBracketIcon,
  FirstBracketCircleIcon,
  FirstBracketSquareIcon,
  SecondBracketIcon,
  SecondBracketCircleIcon,
  SecondBracketSquareIcon,
  ThirdBracketIcon,
  ThirdBracketCircleIcon,
  ThirdBracketSquareIcon,
  AlphaIcon,
  AlphaCircleIcon,
  AlphaSquareIcon,
  BetaIcon,
  AngleIcon,
  Angle01Icon,
  ApproximatelyEqualIcon,
  ApproximatelyEqualCircleIcon,
  ApproximatelyEqualSquareIcon,
  Cone01Icon,
  Cone02Icon,
  CongruentToIcon,
  CongruentToCircleIcon,
  CongruentToSquareIcon,
  Coordinate01Icon,
  Coordinate02Icon,
  CosIcon,
  Cosine01Icon,
  Cosine02Icon,
  CubeIcon,
  Cylinder01Icon,
  Cylinder02Icon,
  Cylinder03Icon,
  Cylinder04Icon,
  Parabola03Icon,
  FunctionOfXIcon,
  // Science icons
  AccelerationIcon,
  BacteriaIcon,
  BlackHoleIcon,
  BlackHole01Icon,
  BoundingBoxIcon,
  CellsIcon,
  GravityIcon,
  MagnetIcon,
  Magnet01Icon,
  Magnet02Icon,
  MoleculesIcon,
  NanoTechnologyIcon,
  PendulumIcon,
  PrismIcon,
  Prism01Icon,
  PulleyIcon,
  Robot01Icon,
  Robot02Icon,
  RoboticIcon,
  SiriIcon,
  SiriNewIcon,
  SolarSystemIcon,
  SolarSystem01Icon,
  SubmergeIcon,
  TestTubeIcon,
  TestTube01Icon,
  TestTube02Icon,
  TestTube03Icon,
  TriangleIcon,
  Triangle01Icon,
  Triangle02Icon,
  Triangle03Icon,
  UfoIcon,
  Ufo01Icon,
  WindTurbineIcon,
  // Computer Science icons
  ApiIcon,
  ApiGatewayIcon,
  AwsLambdaIcon,
  BashIcon,
  BucketIcon,
  Bug01Icon,
  Bug02Icon,
  CProgrammingIcon,
  CppIcon,
  CodeCircleIcon,
  CodeFolderIcon,
  CommandLineIcon,
  ComputerProgramming01Icon,
  ComputerProgramming02Icon,
  ComputerTerminal01Icon,
  ComputerTerminal02Icon,
  // Business icons
  Activity01Icon,
  ActivityCircleIcon,
  AnalysisTextLinkIcon,
  Analytics01Icon,
  AnalyticsDownIcon,
  AnalyticsUpIcon,
  // Gaming icons
  AiGameIcon,
  AircraftGameIcon,
  GameIcon,
  GameboyIcon,
  GameController01Icon,
  GameController02Icon,
  GameController03Icon,
  GamepadDirectionalIcon,
  // Sports icons
  AmericanFootballIcon,
  BaseballIcon,
  BaseballBatIcon,
  BaseballHelmetIcon,
  Basketball01Icon,
  Basketball02Icon,
  BasketballHoopIcon,
  BowlingBallIcon,
  FootballIcon,
  FootballPitchIcon,
  TennisBallIcon,
  VolleyballIcon,
  YogaBallIcon,
  CloudIcon,
} from '@hugeicons/core-free-icons';
import React from 'react';

// Map of icon names to their corresponding Hugeicon components
export const hugeIconMap = {
  // Math & Calculator
  'Calculate': CalculateIcon,
  'Calculator': CalculateIcon,
  'Math': MathIcon,
  'BoardMath': BoardMathIcon,
  'Abacus': AbacusIcon,
  'Absolute': AbsoluteIcon,
  'Acute': AcuteIcon,
  '1stBracket': FirstBracketIcon,
  '1stBracketCircle': FirstBracketCircleIcon,
  '1stBracketSquare': FirstBracketSquareIcon,
  '2ndBracket': SecondBracketIcon,
  '2ndBracketCircle': SecondBracketCircleIcon,
  '2ndBracketSquare': SecondBracketSquareIcon,
  '3rdBracket': ThirdBracketIcon,
  '3rdBracketCircle': ThirdBracketCircleIcon,
  '3rdBracketSquare': ThirdBracketSquareIcon,
  'Alpha': AlphaIcon,
  'AlphaCircle': AlphaCircleIcon,
  'AlphaSquare': AlphaSquareIcon,
  'Beta': BetaIcon,
  'Angle': AngleIcon,
  'Angle01': Angle01Icon,
  'ApproximatelyEqual': ApproximatelyEqualIcon,
  'ApproximatelyEqualCircle': ApproximatelyEqualCircleIcon,
  'ApproximatelyEqualSquare': ApproximatelyEqualSquareIcon,
  'Cone': Cone01Icon,
  'Cone01': Cone01Icon,
  'Cone02': Cone02Icon,
  'CongruentTo': CongruentToIcon,
  'CongruentToCircle': CongruentToCircleIcon,
  'CongruentToSquare': CongruentToSquareIcon,
  'Coordinate': Coordinate01Icon,
  'Coordinate01': Coordinate01Icon,
  'Coordinate02': Coordinate02Icon,
  'Cos': CosIcon,
  'Cosine': Cosine01Icon,
  'Cosine01': Cosine01Icon,
  'Cosine02': Cosine02Icon,
  'Cube': CubeIcon,
  'Cylinder': Cylinder01Icon,
  'Cylinder01': Cylinder01Icon,
  'Cylinder02': Cylinder02Icon,
  'Cylinder03': Cylinder03Icon,
  'Cylinder04': Cylinder04Icon,
  'Parabola03': Parabola03Icon,
  'FunctionOfX': FunctionOfXIcon,

  // Books & Reading
  'Book01': Book01Icon,
  'Book02': Book02Icon,
  'Book03': Book03Icon,
  'Book04': Book04Icon,
  'BookOpen': Book01Icon,
  'Book': Book01Icon,
  'AudioBook01': AudioBook01Icon,
  'AudioBook02': AudioBook02Icon,
  'AudioBook03': AudioBook03Icon,
  'AudioBook04': AudioBook04Icon,

  // Science
  'Atom01': Atom01Icon,
  'Atom02': Atom02Icon,
  'Atom': Atom01Icon,
  'Microscope': MicroscopeIcon,
  'Acceleration': AccelerationIcon,
  'Bacteria': BacteriaIcon,
  'BlackHole': BlackHoleIcon,
  'BlackHole01': BlackHole01Icon,
  'BoundingBox': BoundingBoxIcon,
  'Cells': CellsIcon,
  'Gravity': GravityIcon,
  'Magnet': MagnetIcon,
  'Magnet01': Magnet01Icon,
  'Magnet02': Magnet02Icon,
  'Molecules': MoleculesIcon,
  'NanoTechnology': NanoTechnologyIcon,
  'Nanotechnology': NanoTechnologyIcon,
  'Pendulum': PendulumIcon,
  'Prism': PrismIcon,
  'Prism01': Prism01Icon,
  'Pulley': PulleyIcon,
  'Robot01': Robot01Icon,
  'Robot02': Robot02Icon,
  'Robotic': RoboticIcon,
  'Siri': SiriIcon,
  'SiriNew': SiriNewIcon,
  'SolarSystem': SolarSystemIcon,
  'SolarSystem01': SolarSystem01Icon,
  'Submerge': SubmergeIcon,
  'TestTube': TestTubeIcon,
  'TestTube01': TestTube01Icon,
  'TestTube02': TestTube02Icon,
  'TestTube03': TestTube03Icon,
  'Triangle': TriangleIcon,
  'Triangle01': Triangle01Icon,
  'Triangle02': Triangle02Icon,
  'Triangle03': Triangle03Icon,
  'Ufo': UfoIcon,
  'Ufo01': Ufo01Icon,
  'WindTurbine': WindTurbineIcon,

  // Geography & History
  'Globe': GlobeIcon,
  'Globe02': Globe02Icon,
  'MapsSquare02': MapsSquare02Icon,
  'Maze': MazeIcon,
  'Map': MapsIcon,
  'MoreVertical': MoreVerticalIcon,
  'Compass': CompassIcon,

  // Music
  'MusicNote01': MusicNote01Icon,
  'MusicNote02': MusicNote02Icon,
  'MusicNote03': MusicNote03Icon,
  'MusicNote04': MusicNote04Icon,
  'MusicThree': MusicThreeIcon,
  'FileMusic': FileMusicIcon,
  'File02': File02Icon,
  'FileEmpty02': FileEmpty02Icon,
  'Eye': EyeIcon,
  'Music': MusicNote01Icon,
  'Playlist03': Playlist03Icon,

  // Art & Design
  'Artboard': ArtboardIcon,
  'PenTool01': PenTool01Icon,
  'PenTool02': PenTool02Icon,
  'PenTool03': PenTool03Icon,
  'PenTool': PenTool01Icon,
  'PencilEdit01': PencilEdit01Icon,
  'Pin': PinIcon,
  'PaintBoard': PaintBoardIcon,
  'PisaTower': PisaTowerIcon,
  'Camera01': Camera01Icon,
  'Camera': Camera01Icon,
  'LayoutGrid': LayoutGridIcon,
  'Canvas': CanvasIcon,
  'WebDesign01': WebDesign01Icon,
  'AiMagic': AiMagicIcon,
  'Search01': Search01Icon,
  'Cards01': Cards01Icon,
  'Quiz04': Quiz04Icon,
  'AiContentGenerator02': AiContentGenerator02Icon,
  'Translate': TranslateIcon,
  'Share03': Share03Icon,
  'NewTwitter': NewTwitterIcon,
  'Linkedin02': Linkedin02Icon,
  'Hashtag': HashtagIcon,
  'Blogger': BloggerIcon,
  'MailSend01': MailSend01Icon,
  'UserGroup03': UserGroup03Icon,
  'Chat': ChatIcon,
  'HelpCircle': HelpCircleIcon,
  'GoogleDoc': GoogleDocIcon,
  'FileText': GoogleDocIcon,
  'Video01': Video01Icon,
  'Timer01': Timer01Icon,
  'Clock01': Clock01Icon,
  'Bookmark03': Bookmark03Icon,
  'ChartAnalysis': ChartAnalysisIcon,
  'Wifi02': Wifi02Icon,
  'WifiError02': WifiError02Icon,
  'LogoutCircle02': LogoutCircle02Icon,
  'Settings02': Settings02Icon,
  'ThumbsUp': ThumbsUpIcon,
  'Pen02': Pen02Icon,
  'PlusSign': PlusSignIcon,
  'ArrowDown01': ArrowDown01Icon,
  'ArrowLeft01': ArrowLeft01Icon,
  'ArrowRight01': ArrowRight01Icon,
  'ArrowUp02': ArrowUp02Icon,
  'Play': PlayIcon,
  'Party': PartyIcon,
  'Keyboard': KeyboardIcon,
  'Pause': PauseIcon,
  'Home02': Home02Icon,
  'Calendar02': Calendar02Icon,
  'CalendarRemove01': CalendarRemove01Icon,
  'CalendarMinus02': CalendarMinus02Icon,
  'Filter': FilterIcon,
  'AlertCircle': AlertCircleIcon,
  'CancelCircle': CancelCircleIcon,
  'MinusSignCircle': MinusSignCircleIcon,
  'Delete02': Delete02Icon,
  'Folder02': Folder02Icon,
  'LinkSquare02': LinkSquare02Icon,
  'Folder03': Folder03Icon,
  'FolderAdd': FolderAddIcon,
  'Cancel01': Cancel01Icon,
  'ClipboardPaste': ClipboardPasteIcon,
  'CircleLock01': CircleLock01Icon,
  'Security01': AiSecurity01Icon,
  'WorkHistory': WorkHistoryIcon,
  'CreditCard01': CreditCardIcon,
  'Trophy': CrownIcon,
  'Newspaper': News01Icon,
  'Fingerprint': FingerPrintIcon,
  'Clipboard01': ClipboardIcon,
  'Sparkles': SparklesIcon,
  'VolumeHigh': VolumeHighIcon,
  'Copy01': Copy01Icon,
  'Star': StarIcon,
  'Zap': ZapIcon,
  'CheckmarkCircle02': CheckmarkCircle02Icon,
  'Repeat': RepeatIcon,

  // Technology & Computer Science
  'Code': CodeIcon,
  'CodeSimple': CodeSimpleIcon,
  'CodeSquare': CodeSquareIcon,
  'BinaryCode': BinaryCodeIcon,
  'Laptop': LaptopIcon,
  'Api': ApiIcon,
  'ApiGateway': ApiGatewayIcon,
  'AwsLambda': AwsLambdaIcon,
  'Bash': BashIcon,
  'Bucket': BucketIcon,
  'Bug01': Bug01Icon,
  'Bug02': Bug02Icon,
  'CProgramming': CProgrammingIcon,
  'Cpp': CppIcon,
  'CodeCircle': CodeCircleIcon,
  'CodeFolder': CodeFolderIcon,
  'CommandLine': CommandLineIcon,
  'ComputerProgramming01': ComputerProgramming01Icon,
  'ComputerProgramming02': ComputerProgramming02Icon,
  'ComputerTerminal01': ComputerTerminal01Icon,
  'ComputerTerminal02': ComputerTerminal02Icon,

  // Business
  'Activity01': Activity01Icon,
  'ActivityCircle': ActivityCircleIcon,
  'AnalysisTextLink': AnalysisTextLinkIcon,
  'Analytics01': Analytics01Icon,
  'AnalyticsDown': AnalyticsDownIcon,
  'AnalyticsUp': AnalyticsUpIcon,

  // Gaming
  'AiGame': AiGameIcon,
  'AircraftGame': AircraftGameIcon,
  'Game': GameIcon,
  'Gameboy': GameboyIcon,
  'GameController01': GameController01Icon,
  'GameController02': GameController02Icon,
  'GameController03': GameController03Icon,
  'GamepadDirectional': GamepadDirectionalIcon,

  // Sports
  'AmericanFootball': AmericanFootballIcon,
  'Baseball': BaseballIcon,
  'BaseballBat': BaseballBatIcon,
  'BaseballHelmet': BaseballHelmetIcon,
  'Basketball01': Basketball01Icon,
  'Basketball02': Basketball02Icon,
  'BasketballHoop': BasketballHoopIcon,
  'BowlingBall': BowlingBallIcon,
  'Football': FootballIcon,
  'FootballPitch': FootballPitchIcon,
  'TennisBall': TennisBallIcon,
  'Volleyball': VolleyballIcon,
  'YogaBall': YogaBallIcon,

  // Sports & Activities
  'WorkoutSport': WorkoutSportIcon,
  'EquipmentGym01': EquipmentGym01Icon,
  'EquipmentGym02': EquipmentGym02Icon,
  'EquipmentGym03': EquipmentGym03Icon,
  'Gymnastic': GymnasticIcon,
  'Walking': WalkingIcon,
  'Boat': BoatIcon,
  'Theater': TheaterIcon,
  'TextFont': TextFontIcon,

  // Languages
  'LanguageCircle': LanguageCircleIcon,
  'LanguageSquare': LanguageSquareIcon,
  'LanguageSkill': LanguageSkillIcon,
  'Language': LanguageCircleIcon,
  'Login01': Login01Icon,

  // General Education
  'School': SchoolIcon,
  'School01': School01Icon,
  'GraduationScroll': GraduationScrollIcon,
  'GraduationCap': GraduationScrollIcon,
  'Mortarboard02': Mortarboard02Icon,

  // Other
  'AddressBook': AddressBookIcon,
  'FilePen': FilePenIcon,
  'FileUp': FileUpIcon,
  'Download02': Download02Icon,
  'Rocket': Rocket02Icon,
  'Rotate01': Rotate01Icon,
  'Layout': LayoutIcon,
  'Layers01': Layers01Icon,
  'Archive': ArchiveIcon,
  'LoaderPinwheel': LoaderPinwheelIcon,
  'Crown': CrownIcon,
  'Crown02': Crown02Icon,
  'Crown03': Crown03Icon,
  'Award01': Award01Icon,
  'Sword03': Sword03Icon,
  'UserGroup': UserGroupIcon,
  'UserMultiple': UserMultipleIcon,
  'Users': UserGroupIcon,
  'Wave': WaveIcon,
  'MessageCircle': Message01Icon,
  'Message': Message01Icon,
  'Brain': BrainIcon,
  'Lightbulb': LightbulbOffIcon,
  'Target01': Target01Icon,
  'Target02': Target02Icon,
  'Target': Target01Icon,
  'Link01': Link01Icon,
  'Link02': Link02Icon,
  'Link': Link01Icon,
  'Cloud': CloudIcon,
  'MessageSquare': Message01Icon,
} as const;

export type HugeIconName = keyof typeof hugeIconMap;

// Helper function to get a Hugeicon data by name
export const getHugeIcon = (iconName?: string): any => {
  if (!iconName) return Book01Icon;

  // First try exact match
  if (hugeIconMap[iconName as HugeIconName]) {
    return hugeIconMap[iconName as HugeIconName];
  }

  // Fallback to case-insensitive search
  const lowerIconName = iconName.toLowerCase();
  for (const [key, iconData] of Object.entries(hugeIconMap)) {
    if (key.toLowerCase() === lowerIconName) {
      return iconData;
    }
  }

  // Final fallback
  return Book01Icon;
};

// Helper component to render a Hugeicon with standard props and Lucide fallback
export const HugeIcon: React.FC<{
  name?: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
  fallbackIcon?: React.ComponentType<any>;
}> = ({ name, size = 24, className, style, fallbackIcon }) => {
  const iconData = getHugeIcon(name);

  // Check if we got the default fallback (meaning the icon wasn't found in hugeIconMap)
  const isDefaultFallback = iconData === Book01Icon && name !== 'Book01' && name !== 'BookOpen';

  // If icon not found in hugeIconMap and a fallback icon is provided, use it
  if (isDefaultFallback && fallbackIcon) {
    return React.createElement(fallbackIcon, { size, className, style });
  }

  // Wrap in a div to avoid SVG attribute warnings when style is provided
  if (style) {
    return React.createElement('div', { style, className },
      React.createElement(HugeiconsIcon, { icon: iconData, size })
    );
  }

  return React.createElement(HugeiconsIcon, { icon: iconData, size, className });
};
