import { 
  BookOpen, 
  Book, 
  BookMarked, 
  BookText, 
  BookType, 
  GraduationCap, 
  School, 
  Library, 
  Scroll, 
  Pencil, 
  Edit, 
  FileText, 
  FileEdit, 
  FilePlus2, 
  FileMinus2, 
  FileCheck2, 
  FileX2, 
  FileQuestion, 
  FileSearch, 
  FileClock, 
  FileTerminal, 
  FileCode, 
  FileJson, 
  FileSpreadsheet, 
  FileBarChart2, 
  FileLineChart, 
  FilePieChart,
  Calculator,
  Infinity,
  Percent,
  X,
  XCircle,
  CheckCircle,
  CheckSquare,
  Circle,
  CircleDot,
  CircleDashed,
  CircleEllipsis,
  CircleSlashed,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  XOctagon,
  Diamond,
  Gem,
  // Additional icons for classes
  Video,
  Film,
  TestTube2,
  Microscope,
  Atom,
  Globe,
  Globe2,
  History,
  Music,
  Palette,
  Ruler,
  Code,
  Laptop,
  Brain,
  FlaskConical,
  Cpu,
  Database,
  Gamepad2,
  GitBranch,
  Star,
  Heart,
  HeartPulse,
  ThumbsUp,
  ThumbsDown,
  Flag,
  Tag,
  Hash,
  AtSign,
  Asterisk,
  DollarSign,
  Euro,
  PoundSterling,
  Bitcoin,
  CreditCard,
  Server,
  HardDrive,
  Layers,
  Layout,
  Sidebar,
  Grid,
  List,
  Menu,
  MessageCircle,
  MessageSquare,
  MoreHorizontal,
  MoreVertical,
  Plus,
  Minus,
  Save,
  Download,
  Upload,
  Clipboard,
  Scissors,
  Eraser,
  PenTool
} from 'lucide-react';

// Add missing Pen icon import
import { Pen } from 'lucide-react';

// Map of icon names to their corresponding Lucide icon components
export const iconMap = {
  // School & Education
  'BookOpen': BookOpen,
  'Book': Book,
  'BookMarked': BookMarked,
  'BookText': BookText,
  'BookType': BookType,
  'GraduationCap': GraduationCap,
  'School': School,
  'Library': Library,
  'Scroll': Scroll,
  'Pencil': Pencil,
  'Edit': Edit,
  'FileText': FileText,
  'FileEdit': FileEdit,
  'FilePlus2': FilePlus2,
  'FileMinus2': FileMinus2,
  'FileCheck2': FileCheck2,
  'FileX2': FileX2,
  'FileQuestion': FileQuestion,
  'FileSearch': FileSearch,
  'FileClock': FileClock,
  'FileCode': FileCode,
  'FileJson': FileJson,
  'FileSpreadsheet': FileSpreadsheet,
  'FileBarChart2': FileBarChart2,
  'FileLineChart': FileLineChart,
  'FilePieChart': FilePieChart,
  'Calculator': Calculator,
  'CalculatorIcon': Calculator,
  'Save': Save,
  'Download': Download,
  'Upload': Upload,
  'Clipboard': Clipboard,
  'Globe': Globe,
  'Globe2': Globe2,
  'History': History,
  'Music': Music,
  'Palette': Palette,
  'Ruler': Ruler,
  'Code': Code,
  'Laptop': Laptop,
  'Brain': Brain,
  'FlaskConical': FlaskConical,
  'Flask': FlaskConical, // Alias for FlaskConical
  'Cpu': Cpu,
  'Database': Database,
  'Gamepad2': Gamepad2,
  'GitBranch': GitBranch,
  'Star': Star,
  'Heart': Heart,
  'HeartPulse': HeartPulse,
  'ThumbsUp': ThumbsUp,
  'ThumbsDown': ThumbsDown,
  'DollarSign': DollarSign,
  'Euro': Euro,
  'PoundSterling': PoundSterling,
  'Bitcoin': Bitcoin,
  'CreditCard': CreditCard,
  'Server': Server,
  'HardDrive': HardDrive,
  'Layers': Layers,
  'Layout': Layout,
  'Sidebar': Sidebar,
  'Grid': Grid,
  'List': List,
  'MessageCircle': MessageCircle,
  'MessageSquare': MessageSquare,
  'Menu': Menu,
  'MoreHorizontal': MoreHorizontal,
  'MoreVertical': MoreVertical,
  'Plus': Plus,
  'Minus': Minus,
  'Eraser': Eraser,
  'PenTool': PenTool,
  'Pen': Pen
} as const;

export type IconName = keyof typeof iconMap;
